In [10]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.5.1-cp312-cp312-win_amd64.whl.metadata (12 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\as4761285 001\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (2.1.0)
Collecting scipy>=1.6.0 (from scikit-learn)
  Downloading scipy-1.14.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.8 kB ? eta -:--:--
     ---------------------------------------- 60.8/60.8 kB 1.6 MB/s eta 0:00:00
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.5.1-cp312-cp312-win_amd64.whl (10.9 MB)
   ---------------------------------------- 0.0/10.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.9 MB 5.9 MB/s eta 0:00:02
   -- ------------------------------------- 0.7/10.9 MB 6.0 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/10.9 MB 7.2 MB/s eta 0:00:02
   ----- ---------------------------------- 1.4/10.9 MB 7.5 MB/s eta 0:00:02
   ------- -------------------------------- 2.0/10.9 MB 8.3 MB/s eta 0:00:02
   ---------- ----------------------------- 2.8/10.9 MB 9.9 MB/s eta 0:00:01
   ------------- -------------------------- 3.8/10.9 MB 11.6 MB/s eta 0:00:01
   -------------------- ------------------- 5.6/10.9 MB 14.8 MB/s eta 0:00:01
   ---------------------------- ----------- 7.9/10.9 MB 18.0 MB/s eta 0:00:01
   -------------------------------------- - 10.4/10.9 MB 23.4 MB/s eta 0:00:01
   ---------------------------------------  10.9/10.9 MB 27.3 MB/s eta 0:00:01
   ---------------------------------------- 10.9/10.9 MB 23.4 MB/s eta 0:00:00
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
   ---------------------------------------- 0.0/301.8 kB ? eta -:--:--
   ---------------------------------------- 301.8/301.8 kB ? eta 0:00:00
Downloading scipy-1.14.1-cp312-cp312-win_amd64.whl (44.5 MB)
   ---------------------------------------- 0.0/44.5 MB ? eta -:--:--
   -- ------------------------------------- 3.3/44.5 MB 104.7 MB/s eta 0:00:01
   --- ------------------------------------ 3.4/44.5 MB 36.5 MB/s eta 0:00:02
   --- ------------------------------------ 3.7/44.5 MB 26.2 MB/s eta 0:00:02
   --- ------------------------------------ 4.0/44.5 MB 23.2 MB/s eta 0:00:02
   ------ --------------------------------- 7.2/44.5 MB 32.8 MB/s eta 0:00:02
   ---------- ----------------------------- 11.4/44.5 MB 36.4 MB/s eta 0:00:01
   -------------- ------------------------- 16.0/44.5 MB 81.8 MB/s eta 0:00:01
   ---------------- ----------------------- 18.8/44.5 MB 72.6 MB/s eta 0:00:01
   -------------------- ------------------- 23.2/44.5 MB 93.9 MB/s eta 0:00:01
   -------------------- ------------------- 23.4/44.5 MB 65.6 MB/s eta 0:00:01
   --------------------- ------------------ 23.6/44.5 MB 50.4 MB/s eta 0:00:01
   --------------------- ------------------ 24.0/44.5 MB 40.9 MB/s eta 0:00:01
   ------------------------ --------------- 26.8/44.5 MB 36.4 MB/s eta 0:00:01
   -------------------------- ------------- 29.9/44.5 MB 40.9 MB/s eta 0:00:01
   ----------------------------- ---------- 33.1/44.5 MB 32.8 MB/s eta 0:00:01
   -------------------------------- ------- 36.2/44.5 MB 59.5 MB/s eta 0:00:01
   ---------------------------------- ----- 37.9/44.5 MB 65.6 MB/s eta 0:00:01
   ---------------------------------- ----- 37.9/44.5 MB 54.7 MB/s eta 0:00:01
   ---------------------------------- ----- 38.0/44.5 MB 43.7 MB/s eta 0:00:01
   ---------------------------------- ----- 38.1/44.5 MB 32.8 MB/s eta 0:00:01
   ---------------------------------- ----- 38.2/44.5 MB 29.7 MB/s eta 0:00:01
   ---------------------------------- ----- 38.5/44.5 MB 25.2 MB/s eta 0:00:01
   ----------------------------------- ---- 39.0/44.5 MB 22.6 MB/s eta 0:00:01
   ------------------------------------- -- 41.9/44.5 MB 21.8 MB/s eta 0:00:01
   ---------------------------------------  44.1/44.5 MB 22.6 MB/s eta 0:00:01
   ---------------------------------------  44.5/44.5 MB 22.6 MB/s eta 0:00:01
   ---------------------------------------  44.5/44.5 MB 22.6 MB/s eta 0:00:01
   ---------------------------------------  44.5/44.5 MB 22.6 MB/s eta 0:00:01
   ---------------------------------------  44.5/44.5 MB 22.6 MB/s eta 0:00:01
   ---------------------------------------  44.5/44.5 MB 22.6 MB/s eta 0:00:01
   ---------------------------------------  44.5/44.5 MB 22.6 MB/s eta 0:00:01
   ---------------------------------------  44.5/44.5 MB 22.6 MB/s eta 0:00:01
   ---------------------------------------  44.5/44.5 MB 22.6 MB/s eta 0:00:01
   ---------------------------------------  44.5/44.5 MB 22.6 MB/s eta 0:00:01
   ---------------------------------------  44.5/44.5 MB 22.6 MB/s eta 0:00:01
   ---------------------------------------- 44.5/44.5 MB 10.6 MB/s eta 0:00:00
Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.4.2 scikit-learn-1.5.1 scipy-1.14.1 threadpoolctl-3.5.0

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
from sklearn.datasets import load_iris
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. dropdown:: References\n\n  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n    Mathematical Statistics" (John Wiley, NY, 1950).\n  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n    Structure and Classification Rule for Recognition in Partially Exposed\n    Environments".  IEEE Transactions on Pattern Analysis and Machine\n    Intelligence, Vol. PAMI-2, No. 1, 67-71.\n  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n    on Information Theory, May 1972, 431-433.\n  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n    conceptual clustering system finds 3 classes in the data.\n  - Many, many more ...\n',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

In [13]:
import pandas as pd

In [17]:
data = pd.DataFrame(iris.data,columns = iris.feature_names)
data.insert(0,column = "ID", value = range(150))
data.head()

,ID,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,0,5.1,3.5,1.4,0.2
1,1,4.9,3.0,1.4,0.2
2,2,4.7,3.2,1.3,0.2
3,3,4.6,3.1,1.5,0.2
4,4,5.0,3.6,1.4,0.2

In [18]:
# 구간화
#cut()

cut_data=pd.cut(data["sepal length (cm)"], bins =5 )
data["cut_data"]= cut_data
data.head(10)

,ID,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),cut_data
0,0,5.1,3.5,1.4,0.2,"(5.02, 5.74]"
1,1,4.9,3.0,1.4,0.2,"(4.296, 5.02]"
2,2,4.7,3.2,1.3,0.2,"(4.296, 5.02]"
3,3,4.6,3.1,1.5,0.2,"(4.296, 5.02]"
4,4,5.0,3.6,1.4,0.2,"(4.296, 5.02]"
5,5,5.4,3.9,1.7,0.4,"(5.02, 5.74]"
6,6,4.6,3.4,1.4,0.3,"(4.296, 5.02]"
7,7,5.0,3.4,1.5,0.2,"(4.296, 5.02]"
8,8,4.4,2.9,1.4,0.2,"(4.296, 5.02]"
9,9,4.9,3.1,1.5,0.1,"(4.296, 5.02]"

In [20]:
cut_data_2 = pd.cut(data["sepal length (cm)"], bins =[4,5,6,7,8 ])
data["컷데이터"] = cut_data_2
data.head()

,ID,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),cut_data,컷데이터
0,0,5.1,3.5,1.4,0.2,"(5.02, 5.74]","(5, 6]"
1,1,4.9,3.0,1.4,0.2,"(4.296, 5.02]","(4, 5]"
2,2,4.7,3.2,1.3,0.2,"(4.296, 5.02]","(4, 5]"
3,3,4.6,3.1,1.5,0.2,"(4.296, 5.02]","(4, 5]"
4,4,5.0,3.6,1.4,0.2,"(4.296, 5.02]","(4, 5]"

In [25]:
#qcut

pd.qcut(data["sepal length (cm)"], q = 4)


print(data["sepal length (cm)"].quantile(.25))
print(data["sepal length (cm)"].quantile(.5))
print(data["sepal length (cm)"].quantile(.75))

print(data["petal length (cm)"].max())
print(data["petal length (cm)"].min())

5.1
5.8
6.4
6.9
1.0

In [26]:
pd.qcut(data["sepal length (cm)"], q=10)

0                    (5.0, 5.27]
1                     (4.8, 5.0]
2      (4.2989999999999995, 4.8]
3      (4.2989999999999995, 4.8]
4                     (4.8, 5.0]
                 ...
145                  (6.52, 6.9]
146                   (6.1, 6.3]
147                  (6.3, 6.52]
148                   (6.1, 6.3]
149                   (5.8, 6.1]
Name: sepal length (cm), Length: 150, dtype: category
Categories (10, interval[float64, right]): [(4.2989999999999995, 4.8] < (4.8, 5.0] < (5.0, 5.27] < (5.27, 5.6] ... (6.1, 6.3] < (6.3, 6.52] < (6.52, 6.9] < (6.9, 7.9]]

In [27]:
data["sepal length (cm)"].quantile(.1)

np.float64(4.8)

In [28]:
data["sepal length (cm)"].quantile([0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1])

0.0    4.30
0.1    4.80
0.2    5.00
0.3    5.27
0.4    5.60
0.5    5.80
0.6    6.10
0.7    6.30
0.8    6.52
0.9    6.90
1.0    7.90
Name: sepal length (cm), dtype: float64